# Artificial Neural Network

### Importing the libraries

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'1.14.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8000/8000 [==============================] - 1s 66us/sample - loss: 0.5310 - acc: 0.7747
Epoch 2/100
8000/8000 [==============================] - 0s 40us/sample - loss: 0.4601 - acc: 0.8051
Epoch 3/100
8000/8000 [==============================] - 0s 37us/sample - loss: 0.4358 - acc: 0.8158
Epoch 4/100
8000/8000 [==============================] - 0s 35us/sample - loss: 0.4235 - acc: 0.8227
Epoch 5/100
8000/8000 [==============================] - 0s 38us/sample - loss: 0.4172 - acc: 0.8267
Epoch 6/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.4126 - acc: 0.8278
Epoch 7/100
8000/8000 [==============================] - 0s 37us/sample - loss: 0.4089 - acc: 0.8295
Epoch 8/100
8000/8000 [==============================] - 0s 35us/sample - loss: 0.4060 - acc: 0.8321
Epoch 9/100
8000/8000 [==============================] - 0s 34us/sample - loss: 0.4034 - acc: 0.83

8000/8000 [==============================] - 0s 42us/sample - loss: 0.3417 - acc: 0.8614
Epoch 79/100
8000/8000 [==============================] - 0s 37us/sample - loss: 0.3415 - acc: 0.8604
Epoch 80/100
8000/8000 [==============================] - 0s 49us/sample - loss: 0.3415 - acc: 0.8620
Epoch 81/100
8000/8000 [==============================] - 0s 39us/sample - loss: 0.3410 - acc: 0.8597
Epoch 82/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.3406 - acc: 0.8621
Epoch 83/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.3407 - acc: 0.8611
Epoch 84/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.3400 - acc: 0.8619
Epoch 85/100
8000/8000 [==============================] - 0s 35us/sample - loss: 0.3399 - acc: 0.8626
Epoch 86/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3392 - acc: 0.8618
Epoch 87/100
8000/8000 [==============================] - 0s 34us/sample - loss: 0.3392 - acc: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [22]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[ True]]


In [28]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [29]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 199  206]]


0.859